version: '3.7'

services:

  api:
    container_name: api
    restart: always
    build: .
    ports:
      - "8003:8003"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
  
  db:
    container_name: postgres
    image: postgres:latest
    ports: 
    - "7118:5432"
    environment:
      POSTGRES_DB: 'yukchat'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
    - "./pgdata:/var/lib/postgresql/data"